[project]
name = "beeai-granite4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.13"
dependencies = [
    "beeai-framework>=0.1.53",
    "termcolor>=3.1.0",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "pylint>=3.3.9",
]
